# Generated by Django 5.1 on 2024-11-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organized_by',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
